package com.myapp.struts;
// Generated 24 Mar, 2018 10:28:35 AM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String adminId;
     private String adminName;
     private String userType;

    public Admin() {
    }

	
    public Admin(String adminId) {
        this.adminId = adminId;
    }
    public Admin(String adminId, String adminName, String userType) {
       this.adminId = adminId;
       this.adminName = adminName;
       this.userType = userType;
    }
   
    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }




}


