package com.myapp.struts;
// Generated 24 Mar, 2018 10:28:35 AM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String username;
     private String password;
     private String userType;

    public Login() {
    }

	
    public Login(String username) {
        this.username = username;
    }
    public Login(String username, String password, String userType) {
       this.username = username;
       this.password = password;
       this.userType = userType;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }




}


