package com.myapp.struts;
// Generated 24 Mar, 2018 10:28:35 AM by Hibernate Tools 4.3.1




/**
 * StudentabsentId generated by hbm2java
 */
public class StudentabsentId  implements java.io.Serializable {


     private String studentRegdNo;
     private String batchid;
     private String adate;

    public StudentabsentId() {
    }

    public StudentabsentId(String studentRegdNo, String batchid, String adate) {
       this.studentRegdNo = studentRegdNo;
       this.batchid = batchid;
       this.adate = adate;
    }
   
    public String getStudentRegdNo() {
        return this.studentRegdNo;
    }
    
    public void setStudentRegdNo(String studentRegdNo) {
        this.studentRegdNo = studentRegdNo;
    }
    public String getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }
    public String getAdate() {
        return this.adate;
    }
    
    public void setAdate(String adate) {
        this.adate = adate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentabsentId) ) return false;
		 StudentabsentId castOther = ( StudentabsentId ) other; 
         
		 return ( (this.getStudentRegdNo()==castOther.getStudentRegdNo()) || ( this.getStudentRegdNo()!=null && castOther.getStudentRegdNo()!=null && this.getStudentRegdNo().equals(castOther.getStudentRegdNo()) ) )
 && ( (this.getBatchid()==castOther.getBatchid()) || ( this.getBatchid()!=null && castOther.getBatchid()!=null && this.getBatchid().equals(castOther.getBatchid()) ) )
 && ( (this.getAdate()==castOther.getAdate()) || ( this.getAdate()!=null && castOther.getAdate()!=null && this.getAdate().equals(castOther.getAdate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStudentRegdNo() == null ? 0 : this.getStudentRegdNo().hashCode() );
         result = 37 * result + ( getBatchid() == null ? 0 : this.getBatchid().hashCode() );
         result = 37 * result + ( getAdate() == null ? 0 : this.getAdate().hashCode() );
         return result;
   }   


}


