package com.myapp.struts;
// Generated 24 Mar, 2018 10:28:35 AM by Hibernate Tools 4.3.1



/**
 * Studentattend generated by hbm2java
 */
public class Studentattend  extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private StudentattendId id;
     private Student student;
     private Batch batch;
      private String studentRegdNo;
     private String batchid;
     private String pdate;

    public Studentattend() {
    }

    public Studentattend(StudentattendId id, Student student, Batch batch) {
       this.id = id;
       this.student = student;
       this.batch = batch;
       this.studentRegdNo = studentRegdNo;
       this.batchid=batchid;
       this.pdate=pdate;
    }
   
    public StudentattendId getId() {
        return this.id;
    }
    
    public void setId(StudentattendId id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }

    /**
     * @return the studentRegdNo
     */
    public String getStudentRegdNo() {
        return studentRegdNo;
    }

    /**
     * @param studentRegdNo the studentRegdNo to set
     */
    public void setStudentRegdNo(String studentRegdNo) {
        this.studentRegdNo = studentRegdNo;
    }

    /**
     * @return the batchid
     */
    public String getBatchid() {
        return batchid;
    }

    /**
     * @param batchid the batchid to set
     */
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    /**
     * @return the pdate
     */
    public String getPdate() {
        return pdate;
    }

    /**
     * @param pdate the pdate to set
     */
    public void setPdate(String pdate) {
        this.pdate = pdate;
    }




}


