package com.myapp.struts;
// Generated 24 Mar, 2018 10:28:35 AM by Hibernate Tools 4.3.1




/**
 * StudentattendId generated by hbm2java
 */
public class StudentattendId  implements java.io.Serializable {


     private String studentRegdNo;
     private String batchid;
     private String pdate;

    public StudentattendId() {
    }

    public StudentattendId(String studentRegdNo, String batchid, String pdate) {
       this.studentRegdNo = studentRegdNo;
       this.batchid = batchid;
       this.pdate = pdate;
    }
   
    public String getStudentRegdNo() {
        return this.studentRegdNo;
    }
    
    public void setStudentRegdNo(String studentRegdNo) {
        this.studentRegdNo = studentRegdNo;
    }
    public String getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }
    public String getPdate() {
        return this.pdate;
    }
    
    public void setPdate(String pdate) {
        this.pdate = pdate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentattendId) ) return false;
		 StudentattendId castOther = ( StudentattendId ) other; 
         
		 return ( (this.getStudentRegdNo()==castOther.getStudentRegdNo()) || ( this.getStudentRegdNo()!=null && castOther.getStudentRegdNo()!=null && this.getStudentRegdNo().equals(castOther.getStudentRegdNo()) ) )
 && ( (this.getBatchid()==castOther.getBatchid()) || ( this.getBatchid()!=null && castOther.getBatchid()!=null && this.getBatchid().equals(castOther.getBatchid()) ) )
 && ( (this.getPdate()==castOther.getPdate()) || ( this.getPdate()!=null && castOther.getPdate()!=null && this.getPdate().equals(castOther.getPdate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStudentRegdNo() == null ? 0 : this.getStudentRegdNo().hashCode() );
         result = 37 * result + ( getBatchid() == null ? 0 : this.getBatchid().hashCode() );
         result = 37 * result + ( getPdate() == null ? 0 : this.getPdate().hashCode() );
         return result;
   }   


}


