package com.myapp.struts;
// Generated 24 Mar, 2018 10:28:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private String subjectId;
     private String subjectName;
     private Set teachers = new HashSet(0);

    public Subject() {
    }

	
    public Subject(String subjectId) {
        this.subjectId = subjectId;
    }
    public Subject(String subjectId, String subjectName, Set teachers) {
       this.subjectId = subjectId;
       this.subjectName = subjectName;
       this.teachers = teachers;
    }
   
    public String getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }
    public Set getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set teachers) {
        this.teachers = teachers;
    }




}


